version: "3.9"

services:

  # commenting this since postgres should be the default database, uncomment to use mysql as db layer
  # mysql:
  #   image: mysql
  #   #network_mode: host
  #   ports:
  #     - "3306:3306"
  #   # volumes:
  #   #   - db_data_m:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: SecretPassword
  #     MYSQL_DATABASE: slotracker

  postgres:
    image: postgres
    #network_mode: host
    ports:
      - "5432:5432"
    volumes:
      - db_data_p:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: slotracker
      POSTGRES_PASSWORD: SecretPassword
      POSTGRES_USER: root

  slo-be:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: slo-be:latest
    #network_mode: host
    ports:
      - "80:8080"
    links:
      - postgres
    restart: always
    environment:
      DB_HOST: postgres
      DB_DRIVER: postgres
      DB_PORT: 5432

  slo-fe:
    depends_on:
      - slo-be
    build:
      context: ui/
      dockerfile: Dockerfile
    image: slo-fe:latest
    ports:
      - "3000:80"
    links:
      - slo-be
    restart: always
    environment:
      API_URL: slo-be    
      # Please update username and password if you don't want to use the defaults. 
      USERNAME: admin    
      PASSWORD: admin   

volumes:
  db_data_p: {}
  # db_data_m: {}
 