apiVersion: batch/v1
kind: Job
metadata: 
  name: {{ include "slo-tracker.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: migrations
          image: "{{ .Values.slo-tracker.image.repository }}:{{ .Values.slo-tracker.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - configMapRef:
                name: {{ include "slo-tracker.fullname" . }}-cm
            - secretRef:
                name: {{ include "slo-tracker.fullname" . }}-secret
          {{- with .Values.redmine.migrations.extraEnvs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
          - atlas schema apply --env default
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
