{{- if .Values.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slo-tracker.fullname" $ }}-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed  
type: Opaque
stringData:
  {{- with .Values.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}