{{- if .Values.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slo-tracker.fullname" $ }}-secret
type: Opaque
stringData:
  {{- with .Values.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}